name: MinecraftBot
author: Rafa652
main: me.rafa652.minecraftbot.MinecraftBot
version: 0.96
commands:
    me:
        description: Sends an action, equivalent to IRC's /me
        usage: /me action
    names:
        description: Displays the users on the IRC channel
        usage: /names
    irc:
        description: Does a given IRC action
        usage: /irc op|deop|voice|devoice|kick|connect|rejoin|disconnect
permissions:
    minecraftbot.*:
        description: Gives access to all commands
        children:
            minecraftbot.op: true
            minecraftbot.voice: true
            minecraftbot.kick: true
            minecraftbot.manage: true
    minecraftbot.op:
        description: Gives access to op and deop
    minecraftbot.voice:
        description: Gives access to voice and devoice
    minecraftbot.kick:
        description: Gives access to kick
    minecraftbot.manage:
        description: Gives access to connect, rejoin and disconnect
