#MinecraftBot configuration
#The default values have been filled in for you, but not all required values were filled in.
#Based on the default file, you must add to the server and nick fields before being able to use this plugin.

connection:
#IRC connection settings
  #server: Required. The name of the IRC server. Example: irc.esper.net
  server: ''
  #server_password: Optional. It's very likely that you won't have to change this.
  server_password: ''
  #server_port: The port of the IRC server. Typically 6667. This plugin does not support SSL.
  server_port: 6667
  
  #nick: Required. The nickname for the bot to use. You may set this to anything.
  nick: 'MinecraftBot'
  #nick_password: Optional. The password used to authenticate with NickServ.
  #This password will also be used to attempt to take back the nick using 'ghost' if needed.
  nick_password: ''
  
  #quit_message: The default quit message used when the bot quits IRC. May be left blank.
  quit_message: "See you later."

relay:
#Message relaying settings
  #The following are events from IRC (or the plugin) that will be sent to Minecraft
  to_irc:
    #server: If true, sends messages sent by the "say" console command
    server: true
    #chat: This include regular chat messages and /me messages.
    #To block /me messages, you must use a plugin that blocks people from using the command.
    chat: true
    join: true
    leave: true
    kick: true
    death: true
    
  #The following are events from IRC (or the plugin) that will be sent to Minecraft
  to_minecraft:
    #plugin_log: If true, sends the log messages this plugin generates to MC server
    #ops or those with the 'minecraftbot.manage' permission
    plugin_log: true
    chat: true
    join: true
    part: true
    quit: true
    kick: true
    nick_change: true
    mode_change: true
    topic_change: true

line_formatting:
#You may edit how each line sent by this plugin looks like.
#This plugin does not change how chat is formatted in Minecraft. This is done by other plugins.

#You may enter either IRC or Minecraft color codes into any field.
#The color codes will be automatically 'translated' to the proper values when used.
#For a list of color codes, go to: http://www.minecraftwiki.net/wiki/Classic_server_protocol#Color_Codes
#Replace the & in that article with the section symbol: §

#If you are adding a color to an entire line, keep in mind that the color is reset
#after using a variable. See the default values for examples.

#Depending on the event, there will be different variables available. The default
#values use all the variables available for the event.

  #For messages sent to IRC from Minecraft
  to_irc:
    chat:   '<%name%> %message'
    #action: A /me message
    action: '* %name% %message'
    join:   '§b* %name%§b has joined the game'
    leave:  '§b* %name%§b has left the game'
    kick:   '§c* %name%§c has been kicked (%reason%§c)'
    # The death message cannot be customized as well due to a Bukkit limitation.
    # %name% is also available for this event.
    death:  '§c* %message%'
    
  #For messages sent to Minecraft from IRC
  to_minecraft:
    chat:   '#> <%name%> %message%'
    action: '#> * %name% %message%'
    join:   '#> §b* %name%§b has joined %channel%'
    # At the moment, part messages can't be displayed
    part:   '#> §b* %name%§b has left %channel%'
    quit:   '#> §b* %name%§b has quit IRC (%reason%)'
    kick:   '#> §c* %kicker%§c has kicked %name%§c (%reason%§c)'
    nick_change:  '#> §b* %oldname%§b is now known as %name%'
    mode_change:  '#> §b* %name%§b set mode: %mode%'
    topic_change: '#> §b* %name%§b changed the topic to: §r%topic%'
    
    