#MinecraftBot configuration
#The default values have been filled in for you, but not all required values were filled in.
#Based on the default file, you must add to the server and nick fields before being able to use this plugin.

#Missing values are assumed to be either blank or false.

#It is possible to change the configuration values and apply them while the plugin is active.
#You may do so with the '/minecraftbot reload' command. Note that everything under 'connection'
#is ignored while the plugin is running. The plugin itself must be reloaded to get the new values.

connection:
#IRC connection settings
  #server: Required. The name of the IRC server. Example: irc.esper.net
  server: ''
  #server_password: Optional. It's very likely that you won't have to change this.
  server_password: ''
  #server_port: The port of the IRC server. Typically 6667. This plugin does not support SSL.
  server_port: 6667
  
  #channel: The channel to join. Only one channel may be used.
  channel: ''
  #channel_key: Optional. The key, sometimes called the channel password, required to join the channel.
  channel_key: ''
  
  #nick: Required. The nickname for the bot to use. You may set this to anything.
  nick: 'MinecraftBot'
  #nick_password: Optional. The password used to authenticate with NickServ.
  #This password will also be used to attempt ghosting through NickServ if necessary
  nick_password: ''
  

settings:
#Some extra settings for better control of the bot
#More settings will appear here in future releases
  #ping_developer: Will satisfy the plugin developer's curiosity of how many servers are using this plugin.
  #It sends a bit of data to the developer's server. The data that is sent only contains the version of the
  #server and the version of this plugin. No other data is sent.
  #Data is only sent when the configuration is successfully loaded and when this is set to true.
  ping_developer: true
  #send_log_to_ops: If true, sends log messages generated by this plugin to Minecraft ops or
  #those that have the 'minecraftbot.manage' permission.
  send_log_to_ops: true
  #quit_message: The quit message used when the bot quits IRC. Used only when the plugin is disabled.
  quit_message: ''

line_formatting:
#You may edit how each line sent by this plugin looks like.
#This plugin does not edit the chat formatting in Minecraft.

#You may enter either IRC or Minecraft color codes into any field.
#The color codes will be automatically translated to the appropriate format.
#List of Minecraft color codes: http://www.minecraftwiki.net/wiki/Classic_server_protocol#Color_Codes
#Replace the & with the section symbol: §

#Words that are surrounded by % signs may be used as variables. See the bottom of this file for more details.

#If you are adding a color to an entire line, keep in mind that the color is reset after using a variable.
#See the default values for examples on how to keep one color for the entire line.

#If a formatting line is blank, it is considered disabled and no message will be sent.

  #For messages sent to IRC from Minecraft
  to_irc:
    #server: Messages sent by the "say" console command
    server: '<*Server> %message%'
    chat:   '<%name%> %message%'
    #action: A /me message
    action: '* %name% %message%'
    join:   '§b* %name%§b has joined the game'
    leave:  '§b* %name%§b has left the game'
    kick:   '§c* %name%§c has been kicked (%reason%§c)'
    # The death message cannot be customized as well due to a Bukkit limitation.
    # %name% is also available for this event.
    death:  '§c* %message%'
    
  #For messages sent to Minecraft from IRC
  to_minecraft:
    chat:   '#> <%name%> %message%'
    action: '#> * %name% %message%'
    join:   '#> §b* %name%§b has joined %channel%'
    # At the moment, part messages can't be displayed
    part:   '#> §b* %name%§b has left %channel%'
    quit:   '#> §b* %name%§b has quit IRC (%reason%)'
    kick:   '#> §c* %kicker%§c has kicked %name%§c (%reason%§c)'
    nick_change:  '#> §b* %oldname%§b is now known as %name%'
    mode_change:  '#> §b* %name%§b set mode: %mode%'
    topic_change: '#> §b* %name%§b changed the topic to: §r%message%'

#Some words surrounded by % signs are considered to be variables. When the lines are read by the
#plugin, the variables are replaced by some other value. The variables available per each line are different.
#The default line formatting values use all available variables for that specific line.
#
#There are some variables that are able to get data from other plugins:
#  %faction% - Faction name; Requires the Factions plugin and for the line to have a %name% variable

#If you want more variables, feel free to send a request on the forums (or a pull request on github).
