name: MinecraftBot
author: Rafa652
main: com.avisenera.minecraftbot.MinecraftBot
load: STARTUP
version: 2.0.0
commands:
    names:
        description: Displays the users on the IRC channel
        usage: /names
    n:
        description: Displays the users on the IRC channel
        usage: /n
    irc:
        description: Does a given action on IRC
        usage: /irc say|do|me|op|deop|voice|devoice|kick
    minecraftbot:
        description: Manages the plugin and IRC connection
        usage: /minecraftbot connect|disconnect|rejoin|reload
permissions:
    minecraftbot.op:
        description: Equivalent to having op on IRC. Allows use of the /irc command.
    minecraftbot.manage:
        description: Gives access to the /minecraftbot command.
    minecraftbot.*:
        description: Gives access to all commands
        children:
            minecraftbot.op: true
            minecraftbot.manage: true
