name: MinecraftBot
author: Rafa652
main: com.avisenera.minecraftbot.MinecraftBot
load: STARTUP
version: 1.2.3
commands:
    names:
        description: Displays the users on the IRC channel
        usage: /names
    n:
        description: Displays the users on the IRC channel
        usage: /n
    irc:
        description: Does a given IRC action
        usage: /irc op|deop|voice|devoice|kick|connect|rejoin|disconnect
permissions:
    minecraftbot.op:
        description: Gives access to op and deop
    minecraftbot.voice:
        description: Gives access to voice and devoice
    minecraftbot.kick:
        description: Gives access to kick
    minecraftbot.manage:
        description: Gives access to connect, rejoin and disconnect
    minecraftbot.me:
        description: Anyone using /me will have the text show up on IRC
        default: true
    minecraftbot.*:
        description: Gives access to all commands
        children:
            minecraftbot.op: true
            minecraftbot.voice: true
            minecraftbot.kick: true
            minecraftbot.manage: true
