name: MinecraftBot
author: Rafa652
main: com.avisenera.minecraftbot.MinecraftBot
load: POSTWORLD
version: 2.0.0
commands:
    names:
        description: Displays the users on the IRC channel
        usage: /names
    n:
        description: Displays the users on the IRC channel
        usage: /n
    irc:
        description: Does a given action on IRC
        usage: /irc say|do|me|nick|op|deop|voice|devoice|kick
    minecraftbot:
        description: Manages the plugin and IRC connection
        usage: /minecraftbot connect|disconnect|join|part|reload
permissions:
    minecraftbot.op:
        description: Allows use of the /irc command. Equivalent to having +o in IRC.
    minecraftbot.manage:
        description: Gives access to the /minecraftbot command. See also send_log_to_ops in config.yml
    minecraftbot.*:
        description: Gives access to all commands
        children:
            minecraftbot.op: true
            minecraftbot.manage: true
